name: movie_info_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.5.0+13

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Icons ---
  cupertino_icons: ^1.0.2
  # à¦¸à§à¦²à¦¾à¦‡à¦¡à¦¾à¦°à§‡à¦° à¦œà¦¨à§à¦¯
  carousel_slider: ^5.1.1
  # à¦›à¦¬à¦¿ à¦²à§‹à¦¡ à¦•à¦°à¦¾à¦° à¦œà¦¨à§à¦¯
  cached_network_image: ^3.3.0
  # à¦¤à¦¾à¦°à¦¿à¦– à¦«à¦°à¦®à§à¦¯à¦¾à¦Ÿ à¦•à¦°à¦¾à¦° à¦œà¦¨à§à¦¯
  intl: ^0.18.1

  # --- State Management & Logic ---
  provider: ^6.1.1
  # API à¦•à¦² à¦•à¦°à¦¾à¦° à¦œà¦¨à§à¦¯
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  # à¦²à§‹à¦•à¦¾à¦² à¦¸à§à¦Ÿà§‹à¦°à§‡à¦œ (à¦«à§‡à¦­à¦¾à¦°à¦¿à¦Ÿ à¦¸à§‡à¦­ à¦°à¦¾à¦–à¦¾à¦° à¦œà¦¨à§à¦¯)
  shared_preferences: ^2.2.2
  # à¦²à¦¿à¦‚à¦• à¦“à¦ªà§‡à¦¨ à¦•à¦°à¦¾à¦° à¦œà¦¨à§à¦¯
  url_launcher: ^6.2.2
  # à¦…à§à¦¯à¦¾à¦ª à¦­à¦¾à¦°à§à¦¸à¦¨ à¦¦à§‡à¦–à¦¾à¦° à¦œà¦¨à§à¦¯
  package_info_plus: ^5.0.1
  # à¦›à¦¬à¦¿ à¦¤à§‹à¦²à¦¾à¦° à¦œà¦¨à§à¦¯ (à¦ªà§à¦°à§‹à¦«à¦¾à¦‡à¦² à¦ªà¦¿à¦•à¦šà¦¾à¦°)
  image_picker: ^1.0.7
  
  # --- Firebase & Google Auth ---
  # à¦«à¦¾à§Ÿà¦¾à¦°à¦¬à§‡à¦¸ à¦•à§‹à¦°
  firebase_core: ^2.25.4
  # à¦‡à¦®à§‡à¦‡à¦² à¦²à¦—à¦‡à¦¨
  firebase_auth: ^4.17.4
  # à¦¡à¦¾à¦Ÿà¦¾à¦¬à§‡à¦¸
  cloud_firestore: ^4.15.4
  # à¦¸à§à¦Ÿà§‹à¦°à§‡à¦œ (à¦›à¦¬à¦¿à¦° à¦œà¦¨à§à¦¯)
  firebase_storage: ^11.6.5
  
  # ðŸ”¥ Google Login (à¦à¦‡ à¦­à¦¾à¦°à§à¦¸à¦¨à¦Ÿà¦¿ à¦¸à§à¦Ÿà§‡à¦¬à¦²)
  google_sign_in: ^6.2.1
  introduction_screen: ^3.1.17
  youtube_player_iframe: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # à¦…à§à¦¯à¦¾à¦ª à¦†à¦‡à¦•à¦¨ à¦œà§‡à¦¨à¦¾à¦°à§‡à¦Ÿà¦°
  flutter_launcher_icons: ^0.13.1

# --- Assets & Fonts ---
flutter:
  uses-material-design: true

  # à¦›à¦¬à¦¿ à¦à¦¬à¦‚ à¦à¦¨à¦­à¦¾à§Ÿà¦°à¦¨à¦®à§‡à¦¨à§à¦Ÿ à¦«à¦¾à¦‡à¦²
  assets:
    - .env
    - assets/images/

# à¦…à§à¦¯à¦¾à¦ª à¦†à¦‡à¦•à¦¨ à¦•à¦¨à¦«à¦¿à¦—à¦¾à¦°à§‡à¦¶à¦¨
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-logo.png"
  min_sdk_android: 21